name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2      
      
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag vinaykrg/firstrepo:${{steps.version.outputs.tag}}
        
    - name: Push to Docker Hub
      run: docker push vinaykrg/firstrepo:${{steps.version.outputs.tag}}
